// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/bucketmerge component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bucketmerge")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/bucketmergeprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
